# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milan\Documents\Software Projects\Python Projects\FreeRGB\src\ui\input\InputDialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 200)
        Form.setMinimumSize(QtCore.QSize(400, 200))
        Form.setMaximumSize(QtCore.QSize(400, 200))
        Form.setStyleSheet("background-color: rgb(43, 47, 59);")
        self.input_effect_name = QtWidgets.QLineEdit(Form)
        self.input_effect_name.setGeometry(QtCore.QRect(10, 30, 381, 31))
        self.input_effect_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 58, 72);\n"
"border-radius: 10px;")
        self.input_effect_name.setText("")
        self.input_effect_name.setObjectName("input_effect_name")
        self.input_effect_payload = QtWidgets.QLineEdit(Form)
        self.input_effect_payload.setGeometry(QtCore.QRect(10, 100, 381, 31))
        self.input_effect_payload.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 58, 72);\n"
"border-radius: 10px;")
        self.input_effect_payload.setObjectName("input_effect_payload")
        self.btn_submit = QtWidgets.QPushButton(Form)
        self.btn_submit.setGeometry(QtCore.QRect(274, 152, 111, 31))
        self.btn_submit.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_submit.setObjectName("btn_submit")
        self.label_effect_name = QtWidgets.QLabel(Form)
        self.label_effect_name.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.label_effect_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_effect_name.setObjectName("label_effect_name")
        self.label_effect_payload = QtWidgets.QLabel(Form)
        self.label_effect_payload.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_effect_payload.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_effect_payload.setObjectName("label_effect_payload")
        self.label_error_exists = QtWidgets.QLabel(Form)
        self.label_error_exists.setGeometry(QtCore.QRect(30, 150, 111, 20))
        self.label_error_exists.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_error_exists.setObjectName("label_error_exists")
        self.label_error_blank = QtWidgets.QLabel(Form)
        self.label_error_blank.setGeometry(QtCore.QRect(30, 150, 121, 20))
        self.label_error_blank.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_error_blank.setObjectName("label_error_blank")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_submit.setText(_translate("Form", "Submit"))
        self.label_effect_name.setText(_translate("Form", "Effect Name"))
        self.label_effect_payload.setText(_translate("Form", "Effect Payload"))
        self.label_error_exists.setText(_translate("Form", "Effect Already Exists"))
        self.label_error_blank.setText(_translate("Form", "Entries cannot be blank"))
