# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milan\Documents\Software Projects\Python Projects\FreeRGB\src\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        Form.setMaximumSize(QtCore.QSize(1000, 600))
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 47, 59);")
        self.btn_menu_effects = QtWidgets.QPushButton(Form)
        self.btn_menu_effects.setGeometry(QtCore.QRect(10, 20, 151, 51))
        self.btn_menu_effects.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(27, 27, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(74, 74, 74);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(89, 89, 89);\n"
"    border-radius: 10px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_effects.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_effects.setIcon(icon)
        self.btn_menu_effects.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_effects.setObjectName("btn_menu_effects")
        self.btn_menu_settings = QtWidgets.QPushButton(Form)
        self.btn_menu_settings.setGeometry(QtCore.QRect(10, 90, 151, 51))
        self.btn_menu_settings.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(27, 27, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(74, 74, 74);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(89, 89, 89);\n"
"    border-radius: 10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_settings.setIcon(icon1)
        self.btn_menu_settings.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_settings.setObjectName("btn_menu_settings")
        self.bar_left = QtWidgets.QWidget(Form)
        self.bar_left.setGeometry(QtCore.QRect(0, 0, 171, 601))
        self.bar_left.setStyleSheet("background-color: rgb(27, 27, 35);")
        self.bar_left.setObjectName("bar_left")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bar_left)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bar_bottom = QtWidgets.QWidget(Form)
        self.bar_bottom.setGeometry(QtCore.QRect(170, 540, 831, 61))
        self.bar_bottom.setStyleSheet("background-color: rgb(39, 43, 54);")
        self.bar_bottom.setObjectName("bar_bottom")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bar_bottom)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_effect_off = QtWidgets.QPushButton(Form)
        self.btn_effect_off.setGeometry(QtCore.QRect(950, 550, 41, 41))
        self.btn_effect_off.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(51, 58, 72);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_effect_off.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_effect_off.setIcon(icon2)
        self.btn_effect_off.setIconSize(QtCore.QSize(32, 32))
        self.btn_effect_off.setObjectName("btn_effect_off")
        self.btn_device_information = QtWidgets.QPushButton(Form)
        self.btn_device_information.setGeometry(QtCore.QRect(890, 550, 41, 41))
        self.btn_device_information.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(51, 58, 72);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_device_information.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_device_information.setIcon(icon3)
        self.btn_device_information.setIconSize(QtCore.QSize(32, 32))
        self.btn_device_information.setObjectName("btn_device_information")
        self.btn_list_device = QtWidgets.QPushButton(Form)
        self.btn_list_device.setGeometry(QtCore.QRect(30, 550, 41, 41))
        self.btn_list_device.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(27, 27, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(74, 74, 74);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(89, 89, 89);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_list_device.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_devices.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_list_device.setIcon(icon4)
        self.btn_list_device.setIconSize(QtCore.QSize(32, 32))
        self.btn_list_device.setObjectName("btn_list_device")
        self.btn_list_strip = QtWidgets.QPushButton(Form)
        self.btn_list_strip.setGeometry(QtCore.QRect(100, 550, 41, 41))
        self.btn_list_strip.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(27, 27, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(74, 74, 74);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(89, 89, 89);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_list_strip.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_strips.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_list_strip.setIcon(icon5)
        self.btn_list_strip.setIconSize(QtCore.QSize(32, 32))
        self.btn_list_strip.setObjectName("btn_list_strip")
        self.btn_device_debug = QtWidgets.QPushButton(Form)
        self.btn_device_debug.setGeometry(QtCore.QRect(830, 550, 41, 41))
        self.btn_device_debug.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(51, 58, 72);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_device_debug.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\Milan\\Documents\\Software Projects\\Python Projects\\FreeRGB\\src\\ui\\../assets/icons/ico_debug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_device_debug.setIcon(icon6)
        self.btn_device_debug.setIconSize(QtCore.QSize(32, 32))
        self.btn_device_debug.setObjectName("btn_device_debug")
        self.main_menus = QtWidgets.QStackedWidget(Form)
        self.main_menus.setGeometry(QtCore.QRect(230, 10, 681, 551))
        self.main_menus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.main_menus.setStyleSheet("")
        self.main_menus.setObjectName("main_menus")
        self.menu_effects = QtWidgets.QWidget()
        self.menu_effects.setObjectName("menu_effects")
        self.effects_scroll_region = QtWidgets.QScrollArea(self.menu_effects)
        self.effects_scroll_region.setEnabled(True)
        self.effects_scroll_region.setGeometry(QtCore.QRect(20, 0, 671, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effects_scroll_region.sizePolicy().hasHeightForWidth())
        self.effects_scroll_region.setSizePolicy(sizePolicy)
        self.effects_scroll_region.setMinimumSize(QtCore.QSize(0, 0))
        self.effects_scroll_region.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.effects_scroll_region.setStyleSheet("background-color: rgb(43, 47, 59);")
        self.effects_scroll_region.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.effects_scroll_region.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effects_scroll_region.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effects_scroll_region.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.effects_scroll_region.setWidgetResizable(True)
        self.effects_scroll_region.setObjectName("effects_scroll_region")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 671, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_effect_solid = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_effect_solid.sizePolicy().hasHeightForWidth())
        self.btn_effect_solid.setSizePolicy(sizePolicy)
        self.btn_effect_solid.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_effect_solid.setMaximumSize(QtCore.QSize(700, 100))
        self.btn_effect_solid.setMouseTracking(False)
        self.btn_effect_solid.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_effect_solid.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_effect_solid.setFlat(True)
        self.btn_effect_solid.setObjectName("btn_effect_solid")
        self.verticalLayout_2.addWidget(self.btn_effect_solid)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.btn_effect_rainbowcycle = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_effect_rainbowcycle.sizePolicy().hasHeightForWidth())
        self.btn_effect_rainbowcycle.setSizePolicy(sizePolicy)
        self.btn_effect_rainbowcycle.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_effect_rainbowcycle.setMaximumSize(QtCore.QSize(700, 100))
        self.btn_effect_rainbowcycle.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_effect_rainbowcycle.setObjectName("btn_effect_rainbowcycle")
        self.verticalLayout_2.addWidget(self.btn_effect_rainbowcycle)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.btn_menu_effect_new_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_effect_new_9.sizePolicy().hasHeightForWidth())
        self.btn_menu_effect_new_9.setSizePolicy(sizePolicy)
        self.btn_menu_effect_new_9.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_menu_effect_new_9.setMaximumSize(QtCore.QSize(700, 100))
        self.btn_menu_effect_new_9.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 58, 72);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_menu_effect_new_9.setObjectName("btn_menu_effect_new_9")
        self.verticalLayout_2.addWidget(self.btn_menu_effect_new_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.effects_scroll_region.setWidget(self.scrollAreaWidgetContents_2)
        self.main_menus.addWidget(self.menu_effects)
        self.menu_settings = QtWidgets.QWidget()
        self.menu_settings.setObjectName("menu_settings")
        self.effects_scroll_region_2 = QtWidgets.QScrollArea(self.menu_settings)
        self.effects_scroll_region_2.setGeometry(QtCore.QRect(20, 0, 671, 551))
        self.effects_scroll_region_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.effects_scroll_region_2.setStyleSheet("background-color: rgb(43, 47, 59);")
        self.effects_scroll_region_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.effects_scroll_region_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effects_scroll_region_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effects_scroll_region_2.setWidgetResizable(True)
        self.effects_scroll_region_2.setObjectName("effects_scroll_region_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 671, 666))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.settings_toggle_advanced = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_toggle_advanced.sizePolicy().hasHeightForWidth())
        self.settings_toggle_advanced.setSizePolicy(sizePolicy)
        self.settings_toggle_advanced.setMinimumSize(QtCore.QSize(0, 100))
        self.settings_toggle_advanced.setMaximumSize(QtCore.QSize(700, 100))
        self.settings_toggle_advanced.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(39, 43, 54);\n"
"border-radius: 10px;")
        self.settings_toggle_advanced.setObjectName("settings_toggle_advanced")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.settings_toggle_advanced)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 3, 681, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.settings_toggle_advanced_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.settings_toggle_advanced_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.settings_toggle_advanced_layout.setContentsMargins(0, 0, 0, 0)
        self.settings_toggle_advanced_layout.setObjectName("settings_toggle_advanced_layout")
        spacerItem5 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.settings_toggle_advanced_layout.addItem(spacerItem5)
        self.tmp_layout_settings_advanced = QtWidgets.QHBoxLayout()
        self.tmp_layout_settings_advanced.setObjectName("tmp_layout_settings_advanced")
        self.settings_toggle_advanced_layout.addLayout(self.tmp_layout_settings_advanced)
        self.label_settings_advanced = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_settings_advanced.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_settings_advanced.setObjectName("label_settings_advanced")
        self.settings_toggle_advanced_layout.addWidget(self.label_settings_advanced)
        spacerItem6 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.settings_toggle_advanced_layout.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.settings_toggle_advanced)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.settings_toggle_update = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_toggle_update.sizePolicy().hasHeightForWidth())
        self.settings_toggle_update.setSizePolicy(sizePolicy)
        self.settings_toggle_update.setMinimumSize(QtCore.QSize(0, 100))
        self.settings_toggle_update.setMaximumSize(QtCore.QSize(700, 100))
        self.settings_toggle_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(39, 43, 54);\n"
"border-radius: 10px;")
        self.settings_toggle_update.setObjectName("settings_toggle_update")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.settings_toggle_update)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 3, 681, 102))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.settings_option_update_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.settings_option_update_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.settings_option_update_layout.setContentsMargins(0, 0, 0, 0)
        self.settings_option_update_layout.setObjectName("settings_option_update_layout")
        spacerItem8 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.settings_option_update_layout.addItem(spacerItem8)
        self.tmp_layout_settings_updates = QtWidgets.QHBoxLayout()
        self.tmp_layout_settings_updates.setObjectName("tmp_layout_settings_updates")
        self.settings_option_update_layout.addLayout(self.tmp_layout_settings_updates)
        self.label_settings_update = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_settings_update.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_settings_update.setObjectName("label_settings_update")
        self.settings_option_update_layout.addWidget(self.label_settings_update)
        spacerItem9 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.settings_option_update_layout.addItem(spacerItem9)
        self.verticalLayout_3.addWidget(self.settings_toggle_update)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem10)
        self.btn_support = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_support.sizePolicy().hasHeightForWidth())
        self.btn_support.setSizePolicy(sizePolicy)
        self.btn_support.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_support.setMaximumSize(QtCore.QSize(700, 100))
        self.btn_support.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_support.setObjectName("btn_support")
        self.verticalLayout_3.addWidget(self.btn_support)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem11)
        self.btn_licenses = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_licenses.sizePolicy().hasHeightForWidth())
        self.btn_licenses.setSizePolicy(sizePolicy)
        self.btn_licenses.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_licenses.setMaximumSize(QtCore.QSize(700, 100))
        self.btn_licenses.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_licenses.setObjectName("btn_licenses")
        self.verticalLayout_3.addWidget(self.btn_licenses)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem12)
        self.effects_scroll_region_2.setWidget(self.scrollAreaWidgetContents_3)
        self.main_menus.addWidget(self.menu_settings)
        self.context_menus = QtWidgets.QStackedWidget(Form)
        self.context_menus.setGeometry(QtCore.QRect(20, 340, 121, 191))
        self.context_menus.setStyleSheet("background-color: rgb(27, 27, 35);")
        self.context_menus.setObjectName("context_menus")
        self.context_device = QtWidgets.QWidget()
        self.context_device.setObjectName("context_device")
        self.context_devices = QtWidgets.QScrollArea(self.context_device)
        self.context_devices.setGeometry(QtCore.QRect(0, 0, 121, 191))
        self.context_devices.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(39, 43, 54);\n"
"border-radius: 10px;\n"
"")
        self.context_devices.setWidgetResizable(True)
        self.context_devices.setObjectName("context_devices")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 121, 191))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.stub_device = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.stub_device.setGeometry(QtCore.QRect(10, 20, 101, 30))
        self.stub_device.setMinimumSize(QtCore.QSize(0, 30))
        self.stub_device.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stub_device.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.stub_device.setObjectName("stub_device")
        self.context_devices.setWidget(self.scrollAreaWidgetContents_4)
        self.context_menus.addWidget(self.context_device)
        self.context_strip = QtWidgets.QWidget()
        self.context_strip.setObjectName("context_strip")
        self.context_strips = QtWidgets.QScrollArea(self.context_strip)
        self.context_strips.setGeometry(QtCore.QRect(0, 0, 121, 191))
        self.context_strips.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(39, 43, 54);\n"
"border-radius: 10px;\n"
"")
        self.context_strips.setWidgetResizable(True)
        self.context_strips.setObjectName("context_strips")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 121, 191))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.stub_strip = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.stub_strip.setGeometry(QtCore.QRect(10, 20, 101, 30))
        self.stub_strip.setMinimumSize(QtCore.QSize(0, 30))
        self.stub_strip.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stub_strip.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(90, 164, 253);\n"
"    border-radius: 10px;\n"
"}")
        self.stub_strip.setObjectName("stub_strip")
        self.context_strips.setWidget(self.scrollAreaWidgetContents_5)
        self.context_menus.addWidget(self.context_strip)
        self.btn_version = QtWidgets.QPushButton(Form)
        self.btn_version.setGeometry(QtCore.QRect(180, 550, 101, 41))
        self.btn_version.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 43, 54);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 58, 72);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 76, 100);\n"
"    border-radius: 10px;\n"
"}")
        self.btn_version.setIconSize(QtCore.QSize(32, 32))
        self.btn_version.setObjectName("btn_version")
        self.slider_brightness = QtWidgets.QSlider(Form)
        self.slider_brightness.setGeometry(QtCore.QRect(380, 561, 411, 21))
        self.slider_brightness.setToolTip("")
        self.slider_brightness.setToolTipDuration(2)
        self.slider_brightness.setStatusTip("")
        self.slider_brightness.setWhatsThis("")
        self.slider_brightness.setStyleSheet("QSlider\n"
"{\n"
"    background-color: rgb(39, 43, 54);\n"
"}\n"
"\n"
"QSlider::groove:horizontal\n"
"{ \n"
"    background-color: rgb(27, 27, 35);\n"
"    height: 10px; \n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal\n"
"{ \n"
"    background-color: rgb(51, 58, 72);\n"
"    border: 2px solid rgb(51, 58, 72);\n"
"    width: 16px; \n"
"    height: 16px;\n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover\n"
"{ \n"
"    background-color: rgb(51, 76, 100);\n"
"    border: 2px solid rgb(51, 76, 100);\n"
"    width: 16px; \n"
"    height: 16px;\n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed\n"
"{ \n"
"    background-color: rgb(90, 164, 253);\n"
"    border: 2px solid rgb(90, 164, 253);\n"
"    width: 16px; \n"
"    height: 16px;\n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 10px;\n"
"}")
        self.slider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.slider_brightness.setObjectName("slider_brightness")
        self.main_menus.raise_()
        self.bar_left.raise_()
        self.btn_menu_effects.raise_()
        self.btn_menu_settings.raise_()
        self.btn_list_device.raise_()
        self.btn_list_strip.raise_()
        self.context_menus.raise_()
        self.bar_bottom.raise_()
        self.btn_version.raise_()
        self.btn_device_debug.raise_()
        self.btn_device_information.raise_()
        self.btn_effect_off.raise_()
        self.slider_brightness.raise_()

        self.retranslateUi(Form)
        self.main_menus.setCurrentIndex(0)
        self.context_menus.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_menu_effects.setText(_translate("Form", "  Effects"))
        self.btn_menu_settings.setText(_translate("Form", "  Settings"))
        self.btn_effect_solid.setText(_translate("Form", "Solid Colour"))
        self.btn_effect_rainbowcycle.setText(_translate("Form", "Rainbow Cycle"))
        self.btn_menu_effect_new_9.setText(_translate("Form", "+"))
        self.label_settings_advanced.setText(_translate("Form", "Advanced Mode"))
        self.label_settings_update.setText(_translate("Form", "Check For Updates"))
        self.btn_support.setText(_translate("Form", "Support My Work"))
        self.btn_licenses.setText(_translate("Form", "Open Source Licenses"))
        self.stub_device.setText(_translate("Form", "stub device"))
        self.stub_strip.setText(_translate("Form", "stub strip"))
        self.btn_version.setText(_translate("Form", "Version 0.0.1"))
