# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milan\Documents\Software Projects\Python Projects\FreeRGB\src\ui\views\licenses\LicensesView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        Form.setMinimumSize(QtCore.QSize(800, 500))
        Form.setMaximumSize(QtCore.QSize(800, 500))
        Form.setStyleSheet("background-color: rgb(43, 47, 59);")
        self.license_scroll_region = QtWidgets.QScrollArea(Form)
        self.license_scroll_region.setEnabled(True)
        self.license_scroll_region.setGeometry(QtCore.QRect(70, 0, 651, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.license_scroll_region.sizePolicy().hasHeightForWidth())
        self.license_scroll_region.setSizePolicy(sizePolicy)
        self.license_scroll_region.setMinimumSize(QtCore.QSize(0, 0))
        self.license_scroll_region.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.license_scroll_region.setStyleSheet("background-color: rgb(43, 47, 59);")
        self.license_scroll_region.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.license_scroll_region.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.license_scroll_region.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.license_scroll_region.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.license_scroll_region.setWidgetResizable(True)
        self.license_scroll_region.setObjectName("license_scroll_region")
        self.license_scroll_region_widgets = QtWidgets.QWidget()
        self.license_scroll_region_widgets.setGeometry(QtCore.QRect(0, 0, 651, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.license_scroll_region_widgets.sizePolicy().hasHeightForWidth())
        self.license_scroll_region_widgets.setSizePolicy(sizePolicy)
        self.license_scroll_region_widgets.setMinimumSize(QtCore.QSize(0, 0))
        self.license_scroll_region_widgets.setObjectName("license_scroll_region_widgets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.license_scroll_region_widgets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.license_button_layout = QtWidgets.QVBoxLayout()
        self.license_button_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.license_button_layout.setContentsMargins(-1, -1, 0, -1)
        self.license_button_layout.setSpacing(6)
        self.license_button_layout.setObjectName("license_button_layout")
        self.verticalLayout_3.addLayout(self.license_button_layout)
        self.license_scroll_region.setWidget(self.license_scroll_region_widgets)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
