# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milan\Documents\Software Projects\Python Projects\FreeRGB\src\ui\views\monitor\SerialMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 500)
        Form.setMinimumSize(QtCore.QSize(1000, 500))
        Form.setMaximumSize(QtCore.QSize(1000, 500))
        Form.setStyleSheet("color: rgb(255, 255, 255);")
        self.bottom_bar = QtWidgets.QWidget(Form)
        self.bottom_bar.setGeometry(QtCore.QRect(0, 430, 1001, 71))
        self.bottom_bar.setStyleSheet("background-color: rgb(27, 27, 35);")
        self.bottom_bar.setObjectName("bottom_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottom_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_serial_clear = QtWidgets.QPushButton(Form)
        self.btn_serial_clear.setGeometry(QtCore.QRect(860, 440, 121, 51))
        self.btn_serial_clear.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(27, 27, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color: rgb(89, 89, 89);\n"
"}")
        self.btn_serial_clear.setObjectName("btn_serial_clear")
        self.top_bar = QtWidgets.QWidget(Form)
        self.top_bar.setGeometry(QtCore.QRect(0, 0, 1001, 71))
        self.top_bar.setStyleSheet("background-color: rgb(27, 27, 35);")
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_serial_text = QtWidgets.QLineEdit(Form)
        self.input_serial_text.setGeometry(QtCore.QRect(30, 20, 801, 31))
        self.input_serial_text.setStyleSheet("background-color: rgb(43, 47, 59);\n"
"border-radius: 10px;")
        self.input_serial_text.setText("")
        self.input_serial_text.setObjectName("input_serial_text")
        self.btn_serial_send = QtWidgets.QPushButton(Form)
        self.btn_serial_send.setGeometry(QtCore.QRect(860, 10, 121, 51))
        self.btn_serial_send.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(27, 27, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color: rgb(89, 89, 89);\n"
"}")
        self.btn_serial_send.setObjectName("btn_serial_send")
        self.text_scroll_region = QtWidgets.QScrollArea(Form)
        self.text_scroll_region.setEnabled(True)
        self.text_scroll_region.setGeometry(QtCore.QRect(0, 70, 1001, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_scroll_region.sizePolicy().hasHeightForWidth())
        self.text_scroll_region.setSizePolicy(sizePolicy)
        self.text_scroll_region.setMinimumSize(QtCore.QSize(0, 0))
        self.text_scroll_region.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_scroll_region.setStyleSheet("background-color: rgb(43, 47, 59);")
        self.text_scroll_region.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_scroll_region.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.text_scroll_region.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_scroll_region.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.text_scroll_region.setWidgetResizable(True)
        self.text_scroll_region.setObjectName("text_scroll_region")
        self.text_scroll_region_widgets = QtWidgets.QWidget()
        self.text_scroll_region_widgets.setGeometry(QtCore.QRect(0, 0, 984, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_scroll_region_widgets.sizePolicy().hasHeightForWidth())
        self.text_scroll_region_widgets.setSizePolicy(sizePolicy)
        self.text_scroll_region_widgets.setMinimumSize(QtCore.QSize(0, 0))
        self.text_scroll_region_widgets.setObjectName("text_scroll_region_widgets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.text_scroll_region_widgets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_display = QtWidgets.QLabel(self.text_scroll_region_widgets)
        self.text_display.setText("")
        self.text_display.setObjectName("text_display")
        self.verticalLayout_3.addWidget(self.text_display)
        self.text_scroll_region.setWidget(self.text_scroll_region_widgets)
        self.label_autoscroll = QtWidgets.QLabel(Form)
        self.label_autoscroll.setGeometry(QtCore.QRect(80, 450, 51, 31))
        self.label_autoscroll.setStyleSheet("background-color: rgb(27, 27, 35);")
        self.label_autoscroll.setObjectName("label_autoscroll")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 430, 61, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.switch_placeholder = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.switch_placeholder.setContentsMargins(0, 0, 0, 0)
        self.switch_placeholder.setObjectName("switch_placeholder")
        self.text_scroll_region.raise_()
        self.bottom_bar.raise_()
        self.top_bar.raise_()
        self.input_serial_text.raise_()
        self.btn_serial_send.raise_()
        self.horizontalLayoutWidget.raise_()
        self.btn_serial_clear.raise_()
        self.label_autoscroll.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_serial_clear.setText(_translate("Form", "Clear Output"))
        self.btn_serial_send.setText(_translate("Form", "Send"))
        self.text_scroll_region_widgets.setProperty("style", _translate("Form", "scrollregion"))
        self.label_autoscroll.setText(_translate("Form", "Auto-Scroll"))
